# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    if: "contains(github.event.head_commit.message, '[tag')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: standard-version
        if: "contains(github.event.head_commit.message, '[tag major]')"
        run: nr re-major
        if: "contains(github.event.head_commit.message, '[tag minor]')"
        run: nr re-minor
        if: "contains(github.event.head_commit.message, '[tag patch]')"
        run: nr re-patch
        
      - run: git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: nr release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
